kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-database-hmap-prod-pvc
  namespace: hmap-prod

spec:
  storageClassName: linode-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
