apiVersion: v1
kind: Service
metadata:
  name: pg-database-hmap-prod
  labels:
    app: pg-database-hmap-prod
  namespace: hmap-prod
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app: pg-database-hmap-prod
