# Generated by Django 3.2.7 on 2021-10-18 21:17

import django.core.validators

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Layer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "geojson_data",
                    models.FileField(
                        null=True,
                        upload_to="layers_geojson/",
                        validators=[django.core.validators.FileExtensionValidator(["geojson"])],
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        upload_to="layer_source_files",
                        validators=[django.core.validators.FileExtensionValidator(["csv", "geojson", "kml"])],
                    ),
                ),
                ("style_file", models.FileField(blank=True, null=True, upload_to="")),
                ("is_public", models.BooleanField(default=False)),
            ],
        ),
    ]
