# Generated by Django 3.2.7 on 2021-10-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layer",
            name="style_file",
        ),
        migrations.AddField(
            model_name="layer",
            name="styles",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
