apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-hmap-prod
  name: redis-hmap-prod
  namespace: hmap-prod
  annotations:
    fluxcd.io/automated: "false"
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: redis-hmap-prod
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-hmap-prod
    spec:
      containers:
        - name: redis
          image: redis:6.2.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: redis
              protocol: TCP
              containerPort: 6379
          env:

